sudo: false
language: node_js
node_js: "8"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - rm -rf node_modules/delon

script:
  - npm run pretest
  - npm run test-coverage

after_success:
  - ./node_modules/.bin/codecov
