sudo: required
dist: trusty
language: node_js

node_js:
  - '10.9.0'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

git:
  depth: 1

cache:
  npm: true
  directories:
    - ./node_modules/

before_install:
  - export NG_CLI_ANALYTICS=ci
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

jobs:
  include:
    - stage: pre
      env: 'TASK=build_artifacts'
    - stage: test
      env: 'TASK=test'
    - stage: test
      env: 'TASK=lint'
    - stage: test
      env: 'TASK=site:build'
    - stage: test
      env: 'TASK=build'
    - stage: test
      env: 'TASK=test:cli'

stages:
  - name: pre
    if: branch = master
  - name: test
    if: branch = master

install:
  - chmod +x -R scripts
  - yarn

script:
  - npm run $TASK
  - |
    if [ "$TASK" = "test" ]; then
      cat ./coverage/lcov.info | ./node_modules/.bin/codecov
    fi
